/*=============================================================================
  01-schema.sql — BankDds Full Database Schema
  Generated: 2026-02-18
=============================================================================

  DATABASE TOPOLOGY
  -----------------
  SERVER1  / NGANHANG_BT  : Chi nhánh Bến Thành  (branch code BENTHANH)
  SERVER2  / NGANHANG_TD  : Chi nhánh Tân Định    (branch code TANDINH)
  SERVER3  / NGANHANG     : Bank_Main — central tables, cross-branch views, SPs

  EXECUTION ORDER
  ---------------
  1.  SERVER3  : run SECTION A  (creates CHINHANH, NGUOIDUNG, SEQ_MANV)
  2.  SERVER1  : run SECTION B  targeting NGANHANG_BT
  3.  SERVER2  : run SECTION B  targeting NGANHANG_TD
  4.  All servers: configure Linked Servers per SECTION C (one-time, manual)
  5.  SERVER3  : run SECTION D  (cross-branch views; requires Linked Servers)
  6.  Run 02-seed.sql
  7.  Run sp scripts 10-sp-customers.sql through 15-sp-auth.sql in order

  CONNECTION STRING MAPPING  (appsettings.json)
  -----------------------------------------------
  Branch_BENTHANH → Server=SERVER1;Database=NGANHANG_BT
  Branch_TANDINH  → Server=SERVER2;Database=NGANHANG_TD
  Bank_Main       → Server=SERVER3;Database=NGANHANG
=============================================================================*/


/* =========================================================================
   SECTION A — Bank_Main  (run on SERVER3, database NGANHANG)
   ========================================================================= */

USE NGANHANG;
GO

-- ── Central branch reference table ───────────────────────────────────────────
IF OBJECT_ID('dbo.CHINHANH', 'U') IS NULL
CREATE TABLE dbo.CHINHANH (
    MACN    nChar(10)     NOT NULL,
    TENCN   nvarchar(50)  NOT NULL,
    DIACHI  nvarchar(100) NULL,
    SODT    varchar(15)   NULL,
    CONSTRAINT PK_CHINHANH PRIMARY KEY (MACN)
);
GO

-- ── User accounts (login credentials, stored only on Bank_Main) ───────────────
-- UserGroup: 0 = NganHang | 1 = ChiNhanh | 2 = KhachHang
-- TrangThaiXoa: 0 = Active | 1 = Soft-deleted (GAP-12)
-- PasswordHash: BCrypt hash (cost ≥ 11); generated by BCrypt.Net in the application
IF OBJECT_ID('dbo.NGUOIDUNG', 'U') IS NULL
CREATE TABLE dbo.NGUOIDUNG (
    Username      nvarchar(50)  NOT NULL,
    PasswordHash  nvarchar(255) NOT NULL,
    UserGroup     int           NOT NULL,
    DefaultBranch nvarchar(20)  NOT NULL,
    CustomerCMND  nChar(10)     NULL,
    EmployeeId    nChar(10)     NULL,
    TrangThaiXoa  tinyint       NOT NULL DEFAULT 0,
    CONSTRAINT PK_NGUOIDUNG       PRIMARY KEY (Username),
    CONSTRAINT CK_ND_UserGroup    CHECK (UserGroup    IN (0, 1, 2)),
    CONSTRAINT CK_ND_TTX          CHECK (TrangThaiXoa IN (0, 1))
);
GO

-- ── Sequence: collision-free MANV generation (GAP-13) ────────────────────────
-- Seeds use NV00000001–NV00000004; first generated value = NV00000005.
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE object_id = OBJECT_ID('dbo.SEQ_MANV'))
    CREATE SEQUENCE dbo.SEQ_MANV
        AS int
        START WITH 5
        INCREMENT BY 1
        NO CYCLE;
GO


/* =========================================================================
   SECTION B — Branch Database  (run TWICE: once on SERVER1/NGANHANG_BT,
                                           once on SERVER2/NGANHANG_TD)
   Change the USE statement before each run.
   ========================================================================= */

-- USE NGANHANG_BT;   -- ← uncomment for SERVER1
-- USE NGANHANG_TD;   -- ← uncomment for SERVER2
GO

-- ── Customers ─────────────────────────────────────────────────────────────────
-- CMND: nChar(10), exactly 10 numeric digits (GAP-08 — nChar(10) in DB)
-- TEN:  nvarchar(10)  max 10 chars                       (GAP-09)
-- DIACHI: nvarchar(100) max 100 chars                    (GAP-09)
-- PHAI: N'Nam' or N'Nữ'                                  (GAP-10)
IF OBJECT_ID('dbo.KHACHHANG', 'U') IS NULL
CREATE TABLE dbo.KHACHHANG (
    CMND         nChar(10)     NOT NULL,
    HO           nvarchar(50)  NOT NULL,
    TEN          nvarchar(10)  NOT NULL,
    NGAYSINH     date          NULL,
    DIACHI       nvarchar(100) NULL,
    NGAYCAP      date          NULL,
    SDT          varchar(11)   NULL,
    PHAI         nChar(3)      NOT NULL,
    MACN         nChar(10)     NOT NULL,
    TrangThaiXoa tinyint       NOT NULL DEFAULT 0,
    CONSTRAINT PK_KHACHHANG   PRIMARY KEY (CMND),
    CONSTRAINT CK_KH_PHAI     CHECK (PHAI IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_KH_TTX      CHECK (TrangThaiXoa IN (0, 1))
    -- Cross-server FK to CHINHANH is enforced at application/SP layer only.
    -- Remove if running branch DB standalone without Linked Server SERVER3.
);
GO

-- ── Employees ─────────────────────────────────────────────────────────────────
-- MANV: nChar(10) — 'NV' + 8 zero-padded digits; uniqueness enforced via SEQ_MANV on Bank_Main
IF OBJECT_ID('dbo.NHANVIEN', 'U') IS NULL
CREATE TABLE dbo.NHANVIEN (
    MANV         nChar(10)     NOT NULL,
    HO           nvarchar(50)  NOT NULL,
    TEN          nvarchar(10)  NOT NULL,
    DIACHI       nvarchar(100) NULL,
    CMND         nChar(10)     NULL,
    PHAI         nChar(3)      NOT NULL,
    SDT          varchar(11)   NULL,
    MACN         nChar(10)     NOT NULL,
    TrangThaiXoa tinyint       NOT NULL DEFAULT 0,
    CONSTRAINT PK_NHANVIEN  PRIMARY KEY (MANV),
    CONSTRAINT CK_NV_PHAI   CHECK (PHAI IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_NV_TTX    CHECK (TrangThaiXoa IN (0, 1))
);
GO

-- ── Bank accounts ─────────────────────────────────────────────────────────────
-- SOTK: nChar(9) e.g. 'TK0000001'
-- Status: 'Active' | 'Closed'
IF OBJECT_ID('dbo.TAIKHOAN', 'U') IS NULL
CREATE TABLE dbo.TAIKHOAN (
    SOTK      nChar(9)     NOT NULL,
    CMND      nChar(10)    NOT NULL,
    SODU      money        NOT NULL DEFAULT 0,
    MACN      nChar(10)    NOT NULL,
    NGAYMOTK  date         NOT NULL DEFAULT CAST(GETDATE() AS date),
    Status    nvarchar(10) NOT NULL DEFAULT 'Active',
    CONSTRAINT PK_TAIKHOAN     PRIMARY KEY (SOTK),
    CONSTRAINT CK_TK_SODU      CHECK (SODU >= 0),
    CONSTRAINT CK_TK_STATUS    CHECK (Status IN ('Active', 'Closed')),
    CONSTRAINT FK_TK_KHACHHANG FOREIGN KEY (CMND) REFERENCES dbo.KHACHHANG(CMND)
);
GO

-- ── Sequence: unique MAGD per branch ──────────────────────────────────────────
-- Seed data inserts GD001–GD005 explicitly; generated IDs start at GD000000006.
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE object_id = OBJECT_ID('dbo.SEQ_MAGD'))
    CREATE SEQUENCE dbo.SEQ_MAGD
        AS bigint
        START WITH 6
        INCREMENT BY 1
        NO CYCLE;
GO

-- ── Deposits and withdrawals ──────────────────────────────────────────────────
-- LOAIGD: 'GT' = Gửi tiền (deposit) | 'RT' = Rút tiền (withdrawal)
IF OBJECT_ID('dbo.GD_GOIRUT', 'U') IS NULL
CREATE TABLE dbo.GD_GOIRUT (
    MAGD         nvarchar(20)  NOT NULL,
    SOTK         nChar(9)      NOT NULL,
    LOAIGD       nChar(2)      NOT NULL,
    NGAYGD       datetime      NOT NULL DEFAULT GETDATE(),
    SOTIEN       money         NOT NULL,
    MANV         nChar(10)     NOT NULL,
    Status       nvarchar(10)  NOT NULL DEFAULT 'Completed',
    ErrorMessage nvarchar(500) NULL,
    CONSTRAINT PK_GD_GOIRUT    PRIMARY KEY (MAGD),
    CONSTRAINT CK_GR_LOAIGD    CHECK (LOAIGD IN ('GT', 'RT')),
    CONSTRAINT CK_GR_SOTIEN    CHECK (SOTIEN > 0),
    CONSTRAINT FK_GR_TAIKHOAN  FOREIGN KEY (SOTK) REFERENCES dbo.TAIKHOAN(SOTK)
);
GO

-- ── Fund transfers ────────────────────────────────────────────────────────────
-- SOTK      = source account (the payer; called SOTK_CHUYEN in SP parameters)
-- SOTK_NHAN = destination account (may be on a different branch server — no cross-server FK)
-- LOAIGD is always 'CT' = Chuyển tiền (GAP-03: 'CK' is invalid per DB CHECK constraint)
IF OBJECT_ID('dbo.GD_CHUYENTIEN', 'U') IS NULL
CREATE TABLE dbo.GD_CHUYENTIEN (
    MAGD         nvarchar(20)  NOT NULL,
    SOTK         nChar(9)      NOT NULL,
    SOTK_NHAN    nChar(9)      NOT NULL,
    LOAIGD       nChar(2)      NOT NULL DEFAULT 'CT',
    NGAYGD       datetime      NOT NULL DEFAULT GETDATE(),
    SOTIEN       money         NOT NULL,
    MANV         nChar(10)     NOT NULL,
    Status       nvarchar(10)  NOT NULL DEFAULT 'Completed',
    ErrorMessage nvarchar(500) NULL,
    CONSTRAINT PK_GD_CHUYENTIEN  PRIMARY KEY (MAGD),
    CONSTRAINT CK_CT_LOAIGD      CHECK (LOAIGD = 'CT'),
    CONSTRAINT CK_CT_SOTIEN      CHECK (SOTIEN > 0),
    CONSTRAINT FK_CT_SOTK        FOREIGN KEY (SOTK) REFERENCES dbo.TAIKHOAN(SOTK)
    -- No FK on SOTK_NHAN: cross-branch destination lives on another server.
);
GO


/* =========================================================================
   SECTION C — Linked Server Configuration  (one-time manual setup)
   =========================================================================

   Run on SERVER1 (NGANHANG_BT) to allow outbound calls to SERVER2 and SERVER3:

       EXEC sp_addlinkedserver    @server = N'SERVER2', @srvproduct = N'SQL Server';
       EXEC sp_addlinkedsrvlogin  @rmtsrvname = N'SERVER2', @useself = 'false',
                                  @locallogin = NULL, @rmtuser = N'sa', @rmtpassword = N'123';
       EXEC sp_addlinkedserver    @server = N'SERVER3', @srvproduct = N'SQL Server';
       EXEC sp_addlinkedsrvlogin  @rmtsrvname = N'SERVER3', @useself = 'false',
                                  @locallogin = NULL, @rmtuser = N'sa', @rmtpassword = N'123';

   Repeat symmetrically on SERVER2 (replace SERVER2↔SERVER1).
   Repeat on SERVER3 to reach both SERVER1 and SERVER2.

   For SP_CrossBranchTransfer, MSDTC must be running on all three servers.
   Enable via: Component Services → MSDTC → Security → "Network DTC Access" ON.

   WARNING: Replace 'sa'/'123' with dedicated service accounts for production.
   ========================================================================= */


/* =========================================================================
   SECTION D — Bank_Main cross-branch views  (run on SERVER3 / NGANHANG)
                Requires Linked Servers SERVER1 and SERVER2 from SECTION C.
   ========================================================================= */

USE NGANHANG;
GO

IF OBJECT_ID('dbo.KHACHHANG_ALL',    'V') IS NOT NULL DROP VIEW dbo.KHACHHANG_ALL;
IF OBJECT_ID('dbo.NHANVIEN_ALL',     'V') IS NOT NULL DROP VIEW dbo.NHANVIEN_ALL;
IF OBJECT_ID('dbo.TAIKHOAN_ALL',     'V') IS NOT NULL DROP VIEW dbo.TAIKHOAN_ALL;
IF OBJECT_ID('dbo.GD_GOIRUT_ALL',    'V') IS NOT NULL DROP VIEW dbo.GD_GOIRUT_ALL;
IF OBJECT_ID('dbo.GD_CHUYENTIEN_ALL','V') IS NOT NULL DROP VIEW dbo.GD_CHUYENTIEN_ALL;
GO

CREATE VIEW dbo.KHACHHANG_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].KHACHHANG
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].KHACHHANG;
GO

CREATE VIEW dbo.NHANVIEN_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].NHANVIEN
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].NHANVIEN;
GO

CREATE VIEW dbo.TAIKHOAN_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].TAIKHOAN
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].TAIKHOAN;
GO

CREATE VIEW dbo.GD_GOIRUT_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].GD_GOIRUT
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].GD_GOIRUT;
GO

CREATE VIEW dbo.GD_CHUYENTIEN_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].GD_CHUYENTIEN
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].GD_CHUYENTIEN;
GO
