/*=============================================================================
  01-schema.sql — BankDds Full Database Schema
  Generated: 2026-02-18
=============================================================================

  DATABASE TOPOLOGY  (DE3 – Distributed Banking)
  -----------------------------------------------
  Coordinator (default instance) : DESKTOP-JBB41QU            → DB NGANHANG         (Bank_Main — central tables, views, auth)
  SERVER1  (linked server name)  : DESKTOP-JBB41QU\SQLSERVER2 → DB NGANHANG_BT      (Chi nhánh Bến Thành — BENTHANH)
  SERVER2  (linked server name)  : DESKTOP-JBB41QU\SQLSERVER3 → DB NGANHANG_TD      (Chi nhánh Tân Định  — TANDINH)
  SERVER3  (linked server name)  : DESKTOP-JBB41QU\SQLSERVER4 → DB NGANHANG_TRACUU  (Tra cứu — tổng hợp KH cả 2 CN)

  EXECUTION ORDER
  ---------------
  1.  Coordinator (DESKTOP-JBB41QU)            : run SECTION A  (creates CHINHANH, NGUOIDUNG, SEQ_MANV)
  2.  SERVER1 (DESKTOP-JBB41QU\SQLSERVER2)     : run SECTION B  targeting NGANHANG_BT
  3.  SERVER2 (DESKTOP-JBB41QU\SQLSERVER3)     : run SECTION B  targeting NGANHANG_TD
  4.  All instances: run 16-linked-servers.sql  (Linked Server setup — one-time)
  5.  Coordinator (DESKTOP-JBB41QU)            : run SECTION D  (cross-branch views; requires Linked Servers)
  6.  SERVER3 (DESKTOP-JBB41QU\SQLSERVER4)     : run SECTION E  (TraCuu views; requires Linked Servers)
  7.  Run 02-seed.sql
  8.  Run sp scripts 10-sp-customers.sql through 15-sp-auth.sql in order

  CONNECTION STRING MAPPING  (appsettings.json)
  -----------------------------------------------
  Branch_BENTHANH → Server=DESKTOP-JBB41QU\SQLSERVER2;Database=NGANHANG_BT
  Branch_TANDINH  → Server=DESKTOP-JBB41QU\SQLSERVER3;Database=NGANHANG_TD
  Bank_Main       → Server=DESKTOP-JBB41QU;Database=NGANHANG
=============================================================================*/


/* =========================================================================
   SECTION A — Bank_Main  (run on Coordinator — default instance DESKTOP-JBB41QU, database NGANHANG)
   ========================================================================= */

USE NGANHANG;
GO

-- ── Central branch reference table ───────────────────────────────────────────
IF OBJECT_ID('dbo.CHINHANH', 'U') IS NULL
CREATE TABLE dbo.CHINHANH (
    MACN    nChar(10)     NOT NULL,
    TENCN   nvarchar(100) NOT NULL,
    DIACHI  nvarchar(100) NULL,
    SODT    nvarchar(15)  NULL,
    CONSTRAINT PK_CHINHANH    PRIMARY KEY (MACN),
    CONSTRAINT UQ_CN_TENCN    UNIQUE      (TENCN)
);
GO

-- ── User accounts (login credentials, stored only on Bank_Main) ───────────────
-- UserGroup: 0 = NganHang | 1 = ChiNhanh | 2 = KhachHang
-- TrangThaiXoa: 0 = Active | 1 = Soft-deleted (GAP-12)
-- PasswordHash: BCrypt hash (cost ≥ 11); generated by BCrypt.Net in the application
IF OBJECT_ID('dbo.NGUOIDUNG', 'U') IS NULL
CREATE TABLE dbo.NGUOIDUNG (
    Username      nvarchar(50)  NOT NULL,
    PasswordHash  nvarchar(255) NOT NULL,
    UserGroup     int           NOT NULL,
    DefaultBranch nvarchar(20)  NOT NULL,
    CustomerCMND  nChar(10)     NULL,
    EmployeeId    nChar(10)     NULL,
    TrangThaiXoa  tinyint       NOT NULL DEFAULT 0,
    CONSTRAINT PK_NGUOIDUNG       PRIMARY KEY (Username),
    CONSTRAINT CK_ND_UserGroup    CHECK (UserGroup    IN (0, 1, 2)),
    CONSTRAINT CK_ND_TTX          CHECK (TrangThaiXoa IN (0, 1))
);
GO

-- ── Sequence: collision-free MANV generation (GAP-13) ────────────────────────
-- Seeds use NV00000001–NV00000004; first generated value = NV00000005.
IF NOT EXISTS (SELECT 1 FROM sys.sequences WHERE object_id = OBJECT_ID('dbo.SEQ_MANV'))
    CREATE SEQUENCE dbo.SEQ_MANV
        AS int
        START WITH 5
        INCREMENT BY 1
        NO CYCLE;
GO


/* =========================================================================
   SECTION B — Branch Database  (run TWICE:
     1) Connect to DESKTOP-JBB41QU\SQLSERVER2 → USE NGANHANG_BT  (SERVER1 — BENTHANH)
     2) Connect to DESKTOP-JBB41QU\SQLSERVER3 → USE NGANHANG_TD  (SERVER2 — TANDINH))
   Uncomment the correct USE statement before each run.
   ========================================================================= */

-- USE NGANHANG_BT;   -- ← uncomment when running on DESKTOP-JBB41QU\SQLSERVER2 (SERVER1)
-- USE NGANHANG_TD;   -- ← uncomment when running on DESKTOP-JBB41QU\SQLSERVER3 (SERVER2)
GO

-- ── Customers ─────────────────────────────────────────────────────────────────
-- CMND: nChar(10), exactly 10 numeric digits (GAP-08 — nChar(10) in DB)
-- TEN:  nvarchar(10)  max 10 chars                       (GAP-09)
-- DIACHI: nvarchar(100) max 100 chars                    (GAP-09)
-- PHAI: N'Nam' or N'Nữ'                                  (GAP-10)
IF OBJECT_ID('dbo.KHACHHANG', 'U') IS NULL
CREATE TABLE dbo.KHACHHANG (
    CMND         nChar(10)     NOT NULL,
    HO           nvarchar(50)  NOT NULL,
    TEN          nvarchar(10)  NOT NULL,
    NGAYSINH     date          NULL,
    DIACHI       nvarchar(100) NOT NULL,
    NGAYCAP      date          NOT NULL,
    SODT         nvarchar(15)  NULL,
    PHAI         nChar(3)      NOT NULL,
    MACN         nChar(10)     NOT NULL,
    TrangThaiXoa tinyint       NOT NULL DEFAULT 0,
    CONSTRAINT PK_KHACHHANG   PRIMARY KEY (CMND),
    CONSTRAINT CK_KH_PHAI     CHECK (PHAI IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_KH_TTX      CHECK (TrangThaiXoa IN (0, 1))
    -- Cross-server FK to CHINHANH (on Coordinator/NGANHANG) is enforced at application/SP layer only.
);
GO

-- ── Employees ─────────────────────────────────────────────────────────────────
-- MANV: nChar(10) — 'NV' + 8 zero-padded digits; uniqueness enforced via SEQ_MANV on Bank_Main
IF OBJECT_ID('dbo.NHANVIEN', 'U') IS NULL
CREATE TABLE dbo.NHANVIEN (
    MANV         nChar(10)     NOT NULL,
    HO           nvarchar(50)  NOT NULL,
    TEN          nvarchar(10)  NOT NULL,
    DIACHI       nvarchar(100) NOT NULL,
    CMND         nChar(10)     NOT NULL,
    PHAI         nChar(3)      NOT NULL,
    SODT         nvarchar(15)  NULL,
    MACN         nChar(10)     NOT NULL,
    TrangThaiXoa tinyint       NOT NULL DEFAULT 0,
    CONSTRAINT PK_NHANVIEN    PRIMARY KEY (MANV),
    CONSTRAINT UQ_NV_CMND     UNIQUE      (CMND),
    CONSTRAINT CK_NV_PHAI     CHECK (PHAI IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_NV_TTX      CHECK (TrangThaiXoa IN (0, 1))
);
GO

-- ── Bank accounts ─────────────────────────────────────────────────────────────
-- SOTK: nChar(9) e.g. 'TK0000001'
-- Status: 'Active' | 'Closed'
IF OBJECT_ID('dbo.TAIKHOAN', 'U') IS NULL
CREATE TABLE dbo.TAIKHOAN (
    SOTK      nChar(9)     NOT NULL,
    CMND      nChar(10)    NOT NULL,
    SODU      money        NOT NULL DEFAULT 0,
    MACN      nChar(10)    NOT NULL,
    NGAYMOTK  datetime     NOT NULL DEFAULT GETDATE(),
    Status    nvarchar(10) NOT NULL DEFAULT 'Active',
    CONSTRAINT PK_TAIKHOAN     PRIMARY KEY (SOTK),
    CONSTRAINT CK_TK_SODU      CHECK (SODU >= 0),
    CONSTRAINT CK_TK_STATUS    CHECK (Status IN ('Active', 'Closed')),
    CONSTRAINT FK_TK_KHACHHANG FOREIGN KEY (CMND) REFERENCES dbo.KHACHHANG(CMND)
);
GO

-- ── Deposits and withdrawals ──────────────────────────────────────────────────
-- LOAIGD: 'GT' = Gửi tiền (deposit) | 'RT' = Rút tiền (withdrawal)
-- MAGD: int IDENTITY — DB auto-assigns; no application-side MAGD generation needed.
IF OBJECT_ID('dbo.GD_GOIRUT', 'U') IS NULL
CREATE TABLE dbo.GD_GOIRUT (
    MAGD         int           NOT NULL IDENTITY(1,1),
    SOTK         nChar(9)      NOT NULL,
    LOAIGD       nChar(2)      NOT NULL,
    NGAYGD       datetime      NOT NULL DEFAULT GETDATE(),
    SOTIEN       money         NOT NULL DEFAULT 100000,
    MANV         nChar(10)     NOT NULL,
    Status       nvarchar(10)  NOT NULL DEFAULT 'Completed',
    ErrorMessage nvarchar(500) NULL,
    CONSTRAINT PK_GD_GOIRUT    PRIMARY KEY (MAGD),
    CONSTRAINT CK_GR_LOAIGD    CHECK (LOAIGD IN ('GT', 'RT')),
    CONSTRAINT CK_GR_SOTIEN    CHECK (SOTIEN >= 100000),
    CONSTRAINT FK_GR_TAIKHOAN  FOREIGN KEY (SOTK)  REFERENCES dbo.TAIKHOAN(SOTK),
    CONSTRAINT FK_GR_MANV      FOREIGN KEY (MANV)  REFERENCES dbo.NHANVIEN(MANV)
);
GO

-- ── Fund transfers ────────────────────────────────────────────────────────────
-- SOTK_CHUYEN = source account (the payer)
-- SOTK_NHAN   = destination account (may be on a different branch server — no cross-server FK)
-- LOAIGD is always 'CT' = Chuyển tiền (GAP-03: 'CK' is invalid per DB CHECK constraint)
-- MAGD: int IDENTITY — DB auto-assigns; no application-side MAGD generation needed.
IF OBJECT_ID('dbo.GD_CHUYENTIEN', 'U') IS NULL
CREATE TABLE dbo.GD_CHUYENTIEN (
    MAGD         int           NOT NULL IDENTITY(1,1),
    SOTK_CHUYEN  nChar(9)      NOT NULL,
    SOTK_NHAN    nChar(9)      NOT NULL,
    LOAIGD       nChar(2)      NOT NULL DEFAULT 'CT',
    NGAYGD       datetime      NOT NULL DEFAULT GETDATE(),
    SOTIEN       money         NOT NULL,
    MANV         nChar(10)     NOT NULL,
    Status       nvarchar(10)  NOT NULL DEFAULT 'Completed',
    ErrorMessage nvarchar(500) NULL,
    CONSTRAINT PK_GD_CHUYENTIEN   PRIMARY KEY (MAGD),
    CONSTRAINT CK_CT_LOAIGD       CHECK (LOAIGD = 'CT'),
    CONSTRAINT CK_CT_SOTIEN       CHECK (SOTIEN > 0),
    CONSTRAINT FK_CT_SOTK_CHUYEN  FOREIGN KEY (SOTK_CHUYEN) REFERENCES dbo.TAIKHOAN(SOTK),
    CONSTRAINT FK_CT_MANV         FOREIGN KEY (MANV)        REFERENCES dbo.NHANVIEN(MANV)
    -- No FK on SOTK_NHAN: cross-branch destination lives on another server.
);
GO


/* =========================================================================
   SECTION C — Linked Server Configuration
   =========================================================================

   >>> MOVED TO: 16-linked-servers.sql <<<

   Run 16-linked-servers.sql on each instance in the correct section:
     Section A → Coordinator (DESKTOP-JBB41QU)            — creates SERVER1, SERVER2, SERVER3
     Section B → SERVER1     (DESKTOP-JBB41QU\SQLSERVER2) — creates SERVER2
     Section C → SERVER2     (DESKTOP-JBB41QU\SQLSERVER3) — creates SERVER1
     Section D → SERVER3     (DESKTOP-JBB41QU\SQLSERVER4) — creates SERVER1, SERVER2

   All linked servers use:
     @provider = 'MSOLEDBSQL', @datasrc = <real instance name>
     Login: sa / Password!123
     Options: data access = true, rpc = true, rpc out = true

   For SP_CrossBranchTransfer, MSDTC must be running on all instances.
   Enable via: Component Services → MSDTC → Security → "Network DTC Access" ON.
   ========================================================================= */


/* =========================================================================
   SECTION D — Bank_Main cross-branch views
                (run on Coordinator — default instance DESKTOP-JBB41QU, database NGANHANG)
                Requires Linked Servers SERVER1 and SERVER2 from 16-linked-servers.sql.
   ========================================================================= */

USE NGANHANG;
GO

IF OBJECT_ID('dbo.KHACHHANG_ALL',    'V') IS NOT NULL DROP VIEW dbo.KHACHHANG_ALL;
IF OBJECT_ID('dbo.NHANVIEN_ALL',     'V') IS NOT NULL DROP VIEW dbo.NHANVIEN_ALL;
IF OBJECT_ID('dbo.TAIKHOAN_ALL',     'V') IS NOT NULL DROP VIEW dbo.TAIKHOAN_ALL;
IF OBJECT_ID('dbo.GD_GOIRUT_ALL',    'V') IS NOT NULL DROP VIEW dbo.GD_GOIRUT_ALL;
IF OBJECT_ID('dbo.GD_CHUYENTIEN_ALL','V') IS NOT NULL DROP VIEW dbo.GD_CHUYENTIEN_ALL;
GO

CREATE VIEW dbo.KHACHHANG_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].KHACHHANG
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].KHACHHANG;
GO

CREATE VIEW dbo.NHANVIEN_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].NHANVIEN
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].NHANVIEN;
GO

CREATE VIEW dbo.TAIKHOAN_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].TAIKHOAN
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].TAIKHOAN;
GO

CREATE VIEW dbo.GD_GOIRUT_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].GD_GOIRUT
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].GD_GOIRUT;
GO

CREATE VIEW dbo.GD_CHUYENTIEN_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].GD_CHUYENTIEN
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].GD_CHUYENTIEN;
GO


/* =========================================================================
   SECTION E — TraCuu  (run on SERVER3 — DESKTOP-JBB41QU\SQLSERVER4, database NGANHANG_TRACUU)
                Requires Linked Servers SERVER1 and SERVER2 from 16-linked-servers.sql Section D.
   ========================================================================= */

USE NGANHANG_TRACUU;
GO

IF OBJECT_ID('dbo.V_KHACHHANG_ALL', 'V') IS NOT NULL DROP VIEW dbo.V_KHACHHANG_ALL;
GO

CREATE VIEW dbo.V_KHACHHANG_ALL AS
    SELECT * FROM [SERVER1].[NGANHANG_BT].[dbo].KHACHHANG
    UNION ALL
    SELECT * FROM [SERVER2].[NGANHANG_TD].[dbo].KHACHHANG;
GO
